-- public.customers definition

-- Drop table

-- DROP TABLE public.customers;

CREATE TABLE public.customers (
	segment varchar NULL,
	customer_id varchar(50) NULL,
	customer_name varchar(50) NULL
);

INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','AA-10315','Alex Avila'),
	 ('Consumer','AA-10375','Allen Armold'),
	 ('Consumer','AA-10480','Andrew Allen'),
	 ('Consumer','AA-10645','Anna Andreadi'),
	 ('Consumer','AB-10015','Aaron Bergman'),
	 ('Home Office','AB-10060','Adam Bellavance'),
	 ('Consumer','AB-10105','Adrian Barton'),
	 ('Consumer','AB-10150','Aimee Bixby'),
	 ('Consumer','AB-10165','Alan Barnes'),
	 ('Home Office','AB-10255','Alejandro Ballentine');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','AB-10600','Ann Blume'),
	 ('Corporate','AC-10420','Alyssa Crouse'),
	 ('Consumer','AC-10450','Amy Cox'),
	 ('Corporate','AC-10615','Ann Chong'),
	 ('Consumer','AC-10660','Anna Chung'),
	 ('Home Office','AD-10180','Alan Dominguez'),
	 ('Consumer','AF-10870','Art Ferguson'),
	 ('Consumer','AF-10885','Art Foster'),
	 ('Consumer','AG-10270','Alejandro Grove'),
	 ('Corporate','AG-10300','Aleksandra Gannaway');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','AG-10330','Alex Grayson'),
	 ('Consumer','AG-10390','Allen Goldenen'),
	 ('Corporate','AG-10495','Andrew Gjertsen'),
	 ('Corporate','AG-10525','Andy Gerbode'),
	 ('Consumer','AG-10675','Anna Gayman'),
	 ('Home Office','AG-10765','Anthony Garverick'),
	 ('Consumer','AG-10900','Arthur Gainer'),
	 ('Corporate','AH-10030','Aaron Hawkins'),
	 ('Corporate','AH-10075','Adam Hart'),
	 ('Home Office','AH-10120','Adrian Hane');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','AH-10195','Alan Haines'),
	 ('Consumer','AH-10210','Alan Hwang'),
	 ('Consumer','AH-10465','Amy Hunt'),
	 ('Consumer','AH-10585','Angele Hood'),
	 ('Corporate','AH-10690','Anna Häberlin'),
	 ('Consumer','AI-10855','Arianne Irving'),
	 ('Corporate','AJ-10780','Anthony Jacobs'),
	 ('Corporate','AJ-10795','Anthony Johnson'),
	 ('Consumer','AJ-10945','Ashley Jarboe'),
	 ('Consumer','AJ-10960','Astrea Jones');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','AM-10360','Alice McCarthy'),
	 ('Consumer','AM-10705','Anne McFarland'),
	 ('Corporate','AO-10810','Anthony O''Donnell'),
	 ('Home Office','AP-10720','Anne Pryor'),
	 ('Consumer','AP-10915','Arthur Prichep'),
	 ('Corporate','AR-10345','Alex Russell'),
	 ('Corporate','AR-10405','Allen Rosenblatt'),
	 ('Consumer','AR-10510','Andrew Roberts'),
	 ('Consumer','AR-10540','Andy Reiter'),
	 ('Consumer','AR-10570','Anemone Ratner');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','AR-10825','Anthony Rawles'),
	 ('Corporate','AS-10045','Aaron Smayling'),
	 ('Consumer','AS-10090','Adam Shillingsburg'),
	 ('Home Office','AS-10135','Adrian Shami'),
	 ('Corporate','AS-10225','Alan Schoenberger'),
	 ('Consumer','AS-10240','Alan Shonely'),
	 ('Corporate','AS-10285','Alejandro Savely'),
	 ('Home Office','AS-10630','Ann Steele'),
	 ('Home Office','AT-10435','Alyssa Tate'),
	 ('Consumer','AT-10735','Annie Thurman');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','AW-10840','Anthony Witt'),
	 ('Home Office','AW-10930','Arthur Wiediger'),
	 ('Corporate','AY-10555','Andy Yotov'),
	 ('Consumer','AZ-10750','Annie Zypern'),
	 ('Corporate','BB-10990','Barry Blumstein'),
	 ('Corporate','BB-11545','Brenda Bowman'),
	 ('Home Office','BC-11125','Becky Castell'),
	 ('Consumer','BD-11320','Bill Donatelli'),
	 ('Consumer','BD-11500','Bradley Drucker'),
	 ('Home Office','BD-11560','Brendan Dodson');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','BD-11605','Brian Dahlen'),
	 ('Consumer','BD-11620','Brian DeCherney'),
	 ('Consumer','BD-11635','Brian Derr'),
	 ('Consumer','BD-11725','Bruce Degenhardt'),
	 ('Consumer','BD-11770','Bryan Davis'),
	 ('Home Office','BE-11335','Bill Eplett'),
	 ('Consumer','BE-11410','Bobby Elias'),
	 ('Home Office','BE-11455','Brad Eason'),
	 ('Corporate','BF-10975','Barbara Fisher'),
	 ('Home Office','BF-11005','Barry Franz');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','BF-11020','Barry Französisch'),
	 ('Consumer','BF-11080','Bart Folk'),
	 ('Home Office','BF-11170','Ben Ferrer'),
	 ('Home Office','BF-11215','Benjamin Farhat'),
	 ('Corporate','BF-11275','Beth Fritzler'),
	 ('Consumer','BG-11035','Barry Gonzalez'),
	 ('Corporate','BG-11695','Brooke Gillingham'),
	 ('Consumer','BG-11740','Bruce Geld'),
	 ('Consumer','BH-11710','Brosina Hoffman'),
	 ('Consumer','BK-11260','Berenike Kampe');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','BM-11140','Becky Martin'),
	 ('Corporate','BM-11575','Brendan Murry'),
	 ('Corporate','BM-11650','Brian Moss'),
	 ('Consumer','BM-11785','Bryan Mills'),
	 ('Corporate','BN-11470','Brad Norvell'),
	 ('Consumer','BN-11515','Bradley Nguyen'),
	 ('Corporate','BO-11350','Bill Overfelt'),
	 ('Consumer','BO-11425','Bobby Odegard'),
	 ('Corporate','BP-11050','Barry Pond'),
	 ('Corporate','BP-11095','Bart Pistole');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','BP-11155','Becky Pak'),
	 ('Corporate','BP-11185','Ben Peterman'),
	 ('Consumer','BP-11230','Benjamin Patterson'),
	 ('Consumer','BP-11290','Beth Paige'),
	 ('Corporate','BS-11365','Bill Shonely'),
	 ('Corporate','BS-11380','Bill Stewart'),
	 ('Corporate','BS-11590','Brendan Sweed'),
	 ('Consumer','BS-11665','Brian Stugart'),
	 ('Consumer','BS-11755','Bruce Stewart'),
	 ('Home Office','BS-11800','Bryan Spruell');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Home Office','BT-11305','Beth Thompson'),
	 ('Corporate','BT-11395','Bill Tyler'),
	 ('Consumer','BT-11440','Bobby Trafton'),
	 ('Home Office','BT-11485','Brad Thomas'),
	 ('Home Office','BT-11530','Bradley Talbott'),
	 ('Consumer','BT-11680','Brian Thompson'),
	 ('Corporate','BV-11245','Benjamin Venier'),
	 ('Consumer','BW-11065','Barry Weirich'),
	 ('Corporate','BW-11110','Bart Watters'),
	 ('Consumer','BW-11200','Ben Wallace');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','CA-11965','Carol Adams'),
	 ('Home Office','CA-12055','Cathy Armstrong'),
	 ('Consumer','CA-12265','Christina Anderson'),
	 ('Corporate','CA-12310','Christine Abelman'),
	 ('Consumer','CA-12775','Cynthia Arntzen'),
	 ('Consumer','CB-12025','Cassandra Brandow'),
	 ('Consumer','CB-12415','Christy Brittain'),
	 ('Corporate','CB-12535','Claudia Bergmann'),
	 ('Home Office','CC-12100','Chad Cunningham'),
	 ('Consumer','CC-12145','Charles Crestani');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','CC-12220','Chris Cortes'),
	 ('Consumer','CC-12370','Christopher Conant'),
	 ('Home Office','CC-12430','Chuck Clark'),
	 ('Consumer','CC-12475','Cindy Chapman'),
	 ('Consumer','CC-12550','Clay Cheatham'),
	 ('Corporate','CC-12610','Corey Catlett'),
	 ('Consumer','CC-12670','Craig Carreira'),
	 ('Consumer','CC-12685','Craig Carroll'),
	 ('Consumer','CD-11920','Carlos Daly'),
	 ('Consumer','CD-11980','Carol Darley');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','CD-12280','Christina DeMoss'),
	 ('Home Office','CD-12790','Cynthia Delaney'),
	 ('Home Office','CG-12040','Catherine Glotzbach'),
	 ('Consumer','CG-12520','Claire Gute'),
	 ('Home Office','CH-12070','Cathy Hwang'),
	 ('Corporate','CJ-11875','Carl Jackson'),
	 ('Consumer','CJ-12010','Caroline Jumper'),
	 ('Consumer','CK-12205','Chloris Kastensmidt'),
	 ('Home Office','CK-12325','Christine Kargatis'),
	 ('Consumer','CK-12595','Clytie Kelty');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','CK-12760','Cyma Kinney'),
	 ('Consumer','CL-11890','Carl Ludwig'),
	 ('Consumer','CL-12565','Clay Ludtke'),
	 ('Home Office','CL-12700','Craig Leslie'),
	 ('Corporate','CM-11815','Candace McMahon'),
	 ('Consumer','CM-11935','Carlos Meador'),
	 ('Consumer','CM-12115','Chad McGuire'),
	 ('Consumer','CM-12160','Charles McCrossin'),
	 ('Consumer','CM-12190','Charlotte Melton'),
	 ('Consumer','CM-12235','Chris McAfee');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','CM-12385','Christopher Martinez'),
	 ('Consumer','CM-12445','Chuck Magee'),
	 ('Home Office','CM-12655','Corinna Mitchell'),
	 ('Corporate','CM-12715','Craig Molinari'),
	 ('Consumer','Co-12640','Corey-Lock'),
	 ('Corporate','CP-12085','Cathy Prescott'),
	 ('Corporate','CP-12340','Christine Phan'),
	 ('Home Office','CR-12580','Clay Rozendal'),
	 ('Home Office','CR-12625','Corey Roper'),
	 ('Consumer','CR-12730','Craig Reiter');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Home Office','CR-12820','Cyra Reiten'),
	 ('Corporate','CS-11845','Cari Sayre'),
	 ('Consumer','CS-11860','Cari Schnelling'),
	 ('Consumer','CS-11950','Carlos Soltero'),
	 ('Consumer','CS-12130','Chad Sievert'),
	 ('Corporate','CS-12175','Charles Sheldon'),
	 ('Corporate','CS-12250','Chris Selesnick'),
	 ('Consumer','CS-12355','Christine Sundaresam'),
	 ('Home Office','CS-12400','Christopher Schild'),
	 ('Consumer','CS-12460','Chuck Sachs');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','CS-12490','Cindy Schnelling'),
	 ('Consumer','CS-12505','Cindy Stewart'),
	 ('Consumer','CT-11995','Carol Triggs'),
	 ('Consumer','CV-12295','Christina VanderZanden'),
	 ('Corporate','CV-12805','Cynthia Voltz'),
	 ('Home Office','CW-11905','Carl Weiss'),
	 ('Corporate','CY-12745','Craig Yedwab'),
	 ('Home Office','DA-13450','Dianna Arnett'),
	 ('Home Office','DB-12910','Daniel Byrd'),
	 ('Corporate','DB-12970','Darren Budd');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','DB-13060','Dave Brooks'),
	 ('Corporate','DB-13120','David Bremer'),
	 ('Consumer','DB-13210','Dean Braden'),
	 ('Home Office','DB-13270','Deborah Brumfield'),
	 ('Home Office','DB-13360','Dennis Bolton'),
	 ('Consumer','DB-13405','Denny Blanton'),
	 ('Corporate','DB-13555','Dorothy Badders'),
	 ('Consumer','DB-13615','Doug Bickford'),
	 ('Consumer','DB-13660','Duane Benoit'),
	 ('Consumer','DC-12850','Dan Campbell');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','DC-13285','Debra Catini'),
	 ('Consumer','DD-13570','Dorothy Dickinson'),
	 ('Home Office','DE-13255','Deanra Eno'),
	 ('Consumer','DF-13135','David Flashing'),
	 ('Corporate','DG-13300','Deirdre Greer'),
	 ('Corporate','DH-13075','Dave Hallsten'),
	 ('Home Office','DH-13675','Duane Huffman'),
	 ('Corporate','DJ-13420','Denny Joy'),
	 ('Corporate','DJ-13510','Don Jones'),
	 ('Consumer','DJ-13630','Doug Jacobs');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','DK-12835','Damala Kotsonis'),
	 ('Consumer','DK-12895','Dana Kaydos'),
	 ('Consumer','DK-12985','Darren Koutras'),
	 ('Consumer','DK-13090','Dave Kipp'),
	 ('Corporate','DK-13150','David Kendrick'),
	 ('Corporate','DK-13225','Dean Katz'),
	 ('Consumer','DK-13375','Dennis Kane'),
	 ('Consumer','DL-12865','Dan Lawera'),
	 ('Consumer','DL-12925','Daniel Lacy'),
	 ('Consumer','DL-13315','Delfina Latchford');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','DL-13330','Denise Leinenbach'),
	 ('Corporate','DL-13495','Dionis Lloyd'),
	 ('Corporate','Dl-13600','Dorris liebe'),
	 ('Corporate','DM-12955','Dario Medina'),
	 ('Consumer','DM-13015','Darrin Martin'),
	 ('Corporate','DM-13345','Denise Monton'),
	 ('Corporate','DM-13525','Don Miller'),
	 ('Consumer','DN-13690','Duane Noonan'),
	 ('Consumer','DO-13435','Denny Ordway'),
	 ('Consumer','DO-13645','Doug O''Connell');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','DP-13000','Darren Powers'),
	 ('Corporate','DP-13105','Dave Poirier'),
	 ('Consumer','DP-13165','David Philippe'),
	 ('Home Office','Dp-13240','Dean percer'),
	 ('Home Office','DP-13390','Dennis Pardue'),
	 ('Corporate','DR-12880','Dan Reichenbach'),
	 ('Home Office','DR-12940','Daniel Raglin'),
	 ('Home Office','DS-13030','Darrin Sayre'),
	 ('Corporate','DS-13180','David Smith'),
	 ('Corporate','DV-13045','Darrin Van Huff');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','DV-13465','Dianna Vittorini'),
	 ('Corporate','DW-13195','David Wiener'),
	 ('Home Office','DW-13480','Dianna Wilson'),
	 ('Consumer','DW-13540','Don Weiss'),
	 ('Corporate','DW-13585','Dorothy Wardle'),
	 ('Corporate','EA-14035','Erin Ashbrook'),
	 ('Corporate','EB-13705','Ed Braxton'),
	 ('Corporate','EB-13750','Edward Becker'),
	 ('Corporate','EB-13840','Ellis Ballard'),
	 ('Consumer','EB-13870','Emily Burns');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','EB-13930','Eric Barreto'),
	 ('Corporate','EB-13975','Erica Bern'),
	 ('Consumer','EB-14110','Eugene Barchas'),
	 ('Consumer','EB-14170','Evan Bailliet'),
	 ('Consumer','EC-14050','Erin Creighton'),
	 ('Home Office','ED-13885','Emily Ducich'),
	 ('Consumer','EG-13900','Emily Grady'),
	 ('Corporate','EH-13765','Edward Hooks'),
	 ('Consumer','EH-13945','Eric Hoffmann'),
	 ('Consumer','EH-13990','Erica Hackney');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Home Office','EH-14005','Erica Hernandez'),
	 ('Home Office','EH-14125','Eugene Hildebrand'),
	 ('Consumer','EH-14185','Evan Henry'),
	 ('Consumer','EJ-13720','Ed Jacobs'),
	 ('Consumer','EJ-14155','Eva Jacobs'),
	 ('Home Office','EK-13795','Eileen Kiefer'),
	 ('Home Office','EL-13735','Ed Ludwig'),
	 ('Corporate','EM-13810','Eleni McCrary'),
	 ('Corporate','EM-13825','Elizabeth Moffitt'),
	 ('Consumer','EM-13960','Eric Murdock');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','EM-14065','Erin Mull'),
	 ('Corporate','EM-14095','Eudokia Martin'),
	 ('Home Office','EM-14140','Eugene Moren'),
	 ('Home Office','EM-14200','Evan Minnotte'),
	 ('Consumer','EN-13780','Edward Nazzal'),
	 ('Consumer','EP-13915','Emily Phan'),
	 ('Corporate','ER-13855','Elpida Rittenbach'),
	 ('Consumer','ES-14020','Erica Smith'),
	 ('Corporate','ES-14080','Erin Smith'),
	 ('Corporate','FA-14230','Frank Atkinson');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Home Office','FC-14245','Frank Carlisle'),
	 ('Corporate','FC-14335','Fred Chung'),
	 ('Home Office','FG-14260','Frank Gastineau'),
	 ('Corporate','FH-14275','Frank Hawley'),
	 ('Consumer','FH-14350','Fred Harton'),
	 ('Corporate','FH-14365','Fred Hopkins'),
	 ('Corporate','FM-14215','Filia McAdams'),
	 ('Home Office','FM-14290','Frank Merwin'),
	 ('Consumer','FM-14380','Fred McMath'),
	 ('Consumer','FO-14305','Frank Olsen');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','FP-14320','Frank Preis'),
	 ('Corporate','FW-14395','Fred Wasserman'),
	 ('Consumer','GA-14515','George Ashbrook'),
	 ('Consumer','GA-14725','Guy Armstrong'),
	 ('Corporate','GB-14530','George Bell'),
	 ('Consumer','GB-14575','Giulietta Baptist'),
	 ('Corporate','GD-14590','Giulietta Dortch'),
	 ('Corporate','GG-14650','Greg Guthrie'),
	 ('Home Office','GH-14410','Gary Hansen'),
	 ('Consumer','GH-14425','Gary Hwang');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','GH-14485','Gene Hale'),
	 ('Consumer','GH-14665','Greg Hansen'),
	 ('Corporate','GK-14620','Grace Kelly'),
	 ('Consumer','GM-14440','Gary McGarr'),
	 ('Home Office','GM-14455','Gary Mitchum'),
	 ('Consumer','GM-14500','Gene McClure'),
	 ('Consumer','GM-14680','Greg Matthias'),
	 ('Corporate','GM-14695','Greg Maxwell'),
	 ('Corporate','GP-14740','Guy Phonely'),
	 ('Corporate','GR-14560','Georgia Rosenberg');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','GT-14635','Grant Thornton'),
	 ('Consumer','GT-14710','Greg Tran'),
	 ('Consumer','GT-14755','Guy Thornton'),
	 ('Consumer','GW-14605','Giulietta Weimer'),
	 ('Consumer','GZ-14470','Gary Zandusky'),
	 ('Corporate','GZ-14545','George Zrebassa'),
	 ('Consumer','HA-14905','Helen Abelman'),
	 ('Consumer','HA-14920','Helen Andreada'),
	 ('Home Office','HD-14785','Harold Dahlen'),
	 ('Corporate','HE-14800','Harold Engle');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','HF-14995','Herbert Flentye'),
	 ('Consumer','HG-14845','Harry Greene'),
	 ('Corporate','HG-14965','Henry Goldwyn'),
	 ('Consumer','HG-15025','Hunter Glantz'),
	 ('Corporate','HH-15010','Hilary Holden'),
	 ('Home Office','HJ-14875','Heather Jas'),
	 ('Corporate','HK-14890','Heather Kirkland'),
	 ('Consumer','HL-15040','Hunter Lopez'),
	 ('Corporate','HM-14860','Harry Marie'),
	 ('Consumer','HM-14980','Henry MacAllister');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Home Office','HP-14815','Harold Pawlan'),
	 ('Home Office','HR-14770','Hallie Redmond'),
	 ('Corporate','HR-14830','Harold Ryan'),
	 ('Corporate','HW-14935','Helen Wasserman'),
	 ('Consumer','HZ-14950','Henia Zydlo'),
	 ('Consumer','IG-15085','Ivan Gibson'),
	 ('Consumer','IL-15100','Ivan Liston'),
	 ('Consumer','IM-15055','Ionia McGrath'),
	 ('Consumer','IM-15070','Irene Maddox'),
	 ('Consumer','JA-15970','Joseph Airdo');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','JB-15400','Jennifer Braxton'),
	 ('Consumer','JB-15925','Joni Blumstein'),
	 ('Consumer','JB-16000','Joy Bell-'),
	 ('Home Office','JB-16045','Julia Barnett'),
	 ('Consumer','JC-15340','Jasper Cacioppo'),
	 ('Consumer','JC-15385','Jenna Caffey'),
	 ('Consumer','JC-15775','John Castell'),
	 ('Corporate','JC-16105','Julie Creighton'),
	 ('Consumer','JD-15790','John Dryer'),
	 ('Corporate','JD-15895','Jonathan Doherty');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','JD-16015','Joy Daniels'),
	 ('Consumer','JD-16060','Julia Dunbar'),
	 ('Corporate','JD-16150','Justin Deggeller'),
	 ('Consumer','JE-15475','Jeremy Ellison'),
	 ('Corporate','JE-15610','Jim Epp'),
	 ('Consumer','JE-15715','Joe Elijah'),
	 ('Consumer','JE-15745','Joel Eaton'),
	 ('Corporate','JE-16165','Justin Ellison'),
	 ('Consumer','JF-15190','Jamie Frazer'),
	 ('Consumer','JF-15295','Jason Fortune-');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','JF-15355','Jay Fein'),
	 ('Consumer','JF-15415','Jennifer Ferguson'),
	 ('Consumer','JF-15490','Jeremy Farry'),
	 ('Consumer','JF-15565','Jill Fjeld'),
	 ('Consumer','JG-15115','Jack Garza'),
	 ('Consumer','JG-15160','James Galang'),
	 ('Corporate','JG-15310','Jason Gross'),
	 ('Corporate','JG-15805','John Grady'),
	 ('Consumer','JH-15430','Jennifer Halladay'),
	 ('Consumer','JH-15820','John Huston');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','JH-15910','Jonathan Howell'),
	 ('Consumer','JH-15985','Joseph Holt'),
	 ('Consumer','JH-16180','Justin Hirsh'),
	 ('Consumer','JJ-15445','Jennifer Jackson'),
	 ('Home Office','JJ-15760','Joel Jenkins'),
	 ('Consumer','JK-15205','Jamie Kunitz'),
	 ('Corporate','JK-15325','Jason Klamczynski'),
	 ('Consumer','JK-15370','Jay Kimmel'),
	 ('Consumer','JK-15625','Jim Karlsson'),
	 ('Home Office','JK-15640','Jim Kriz');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','JK-15730','Joe Kamberova'),
	 ('Consumer','JK-16090','Juliana Krohn'),
	 ('Home Office','JK-16120','Julie Kriz'),
	 ('Consumer','JL-15130','Jack Lebron'),
	 ('Home Office','JL-15175','James Lanier'),
	 ('Consumer','JL-15235','Janet Lee'),
	 ('Consumer','JL-15505','Jeremy Lonsdale'),
	 ('Consumer','JL-15835','John Lee'),
	 ('Consumer','JL-15850','John Lucas'),
	 ('Consumer','JM-15250','Janet Martin');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','JM-15265','Janet Molinari'),
	 ('Consumer','JM-15535','Jessica Myrick'),
	 ('Consumer','JM-15580','Jill Matthias'),
	 ('Corporate','JM-15655','Jim Mitchum'),
	 ('Consumer','JM-15865','John Murray'),
	 ('Consumer','JM-16195','Justin MacKendrick'),
	 ('Corporate','JO-15145','Jack O''Briant'),
	 ('Consumer','JO-15280','Jas O''Carroll'),
	 ('Home Office','JO-15550','Jesus Ocampo'),
	 ('Corporate','JP-15460','Jennifer Patt');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','JP-15520','Jeremy Pistek'),
	 ('Home Office','JP-16135','Julie Prescott'),
	 ('Consumer','JR-15670','Jim Radford'),
	 ('Consumer','JR-15700','Jocasta Rupert'),
	 ('Corporate','JR-16210','Justin Ritter'),
	 ('Corporate','JS-15595','Jill Stevenson'),
	 ('Corporate','JS-15685','Jim Sink'),
	 ('Consumer','JS-15880','John Stevenson'),
	 ('Home Office','JS-15940','Joni Sundaresam'),
	 ('Consumer','JS-16030','Joy Smith');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','JW-15220','Jane Waco'),
	 ('Consumer','JW-15955','Joni Wasserman'),
	 ('Consumer','JW-16075','Julia West'),
	 ('Consumer','KA-16525','Kelly Andreada'),
	 ('Corporate','KB-16240','Karen Bern'),
	 ('Consumer','KB-16315','Karl Braun'),
	 ('Home Office','KB-16405','Katrina Bavinger'),
	 ('Corporate','KB-16585','Ken Black'),
	 ('Corporate','KB-16600','Ken Brennan'),
	 ('Corporate','KC-16255','Karen Carlisle');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','KC-16540','Kelly Collister'),
	 ('Corporate','KC-16675','Kimberly Carter'),
	 ('Consumer','KD-16270','Karen Daniels'),
	 ('Consumer','KD-16345','Katherine Ducich'),
	 ('Corporate','KD-16495','Keith Dawkins'),
	 ('Corporate','KD-16615','Ken Dana'),
	 ('Corporate','KE-16420','Katrina Edelman'),
	 ('Home Office','KF-16285','Karen Ferguson'),
	 ('Corporate','KH-16330','Katharine Harms'),
	 ('Consumer','KH-16360','Katherine Hughes');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','KH-16510','Keith Herrera'),
	 ('Corporate','KH-16630','Ken Heidel'),
	 ('Corporate','KH-16690','Kristen Hastings'),
	 ('Corporate','KL-16555','Kelly Lampkin'),
	 ('Consumer','KL-16645','Ken Lonsdale'),
	 ('Corporate','KM-16225','Kalyca Meade'),
	 ('Home Office','KM-16375','Katherine Murray'),
	 ('Consumer','KM-16660','Khloe Miller'),
	 ('Consumer','KM-16720','Kunst Miller'),
	 ('Corporate','KN-16390','Katherine Nockton');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','KN-16450','Kean Nguyen'),
	 ('Home Office','KN-16705','Kristina Nunn'),
	 ('Corporate','KS-16300','Karen Seio'),
	 ('Consumer','KT-16465','Kean Takahito'),
	 ('Consumer','KT-16480','Kean Thornton'),
	 ('Consumer','KW-16435','Katrina Willman'),
	 ('Consumer','KW-16570','Kelly Williams'),
	 ('Corporate','LA-16780','Laura Armstrong'),
	 ('Consumer','LB-16735','Larry Blacks'),
	 ('Home Office','LB-16795','Laurel Beltran');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','LC-16870','Lena Cacioppo'),
	 ('Consumer','LC-16885','Lena Creighton'),
	 ('Corporate','LC-16930','Linda Cazamias'),
	 ('Home Office','LC-16960','Lindsay Castell'),
	 ('Consumer','LC-17050','Liz Carlisle'),
	 ('Consumer','LC-17140','Logan Currie'),
	 ('Corporate','LD-16855','Lela Donovan'),
	 ('Consumer','LD-17005','Lisa DeCherney'),
	 ('Consumer','LE-16810','Laurel Elliston'),
	 ('Consumer','LF-17185','Luke Foster');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','LH-16750','Larry Hughes'),
	 ('Consumer','LH-16900','Lena Hernandez'),
	 ('Consumer','LH-17020','Lisa Hazard'),
	 ('Consumer','LH-17155','Logan Haushalter'),
	 ('Consumer','LL-16840','Lauren Leatherbury'),
	 ('Consumer','LM-17065','Liz MacKendrick'),
	 ('Corporate','LO-17170','Lori Olson'),
	 ('Consumer','LP-17080','Liz Pelletier'),
	 ('Consumer','LP-17095','Liz Preis'),
	 ('Consumer','LR-16915','Lena Radford');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','LR-17035','Lisa Ryan'),
	 ('Corporate','LS-16945','Linda Southworth'),
	 ('Home Office','LS-16975','Lindsay Shagiari'),
	 ('Corporate','LS-17200','Luke Schmidt'),
	 ('Consumer','LS-17230','Lycoris Saunders'),
	 ('Consumer','LS-17245','Lynn Smith'),
	 ('Consumer','LT-16765','Larry Tron'),
	 ('Consumer','LT-17110','Liz Thompson'),
	 ('Corporate','LW-16825','Laurel Workman'),
	 ('Corporate','LW-16990','Lindsay Williams');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','LW-17125','Liz Willingham'),
	 ('Consumer','LW-17215','Luke Weiss'),
	 ('Home Office','MA-17560','Matt Abelman'),
	 ('Home Office','MA-17995','Michelle Arnett'),
	 ('Consumer','MB-17305','Maria Bertelson'),
	 ('Consumer','MB-18085','Mick Brown'),
	 ('Consumer','MC-17275','Marc Crier'),
	 ('Corporate','MC-17425','Mark Cousins'),
	 ('Consumer','MC-17575','Matt Collins'),
	 ('Corporate','MC-17590','Matt Collister');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','MC-17605','Matt Connell'),
	 ('Corporate','MC-17635','Matthew Clasen'),
	 ('Consumer','MC-17845','Michael Chen'),
	 ('Consumer','MC-18100','Mick Crebagga'),
	 ('Corporate','MC-18130','Mike Caudle'),
	 ('Consumer','MD-17350','Maribeth Dona'),
	 ('Corporate','MD-17860','Michael Dominguez'),
	 ('Home Office','ME-17320','Maria Etezadi'),
	 ('Consumer','ME-17725','Max Engle'),
	 ('Corporate','ME-18010','Michelle Ellison');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','MF-17665','Maureen Fritzler'),
	 ('Corporate','MF-18250','Monica Federle'),
	 ('Home Office','MG-17650','Matthew Grinstein'),
	 ('Home Office','MG-17680','Maureen Gastineau'),
	 ('Consumer','MG-17695','Maureen Gnade'),
	 ('Home Office','MG-17875','Michael Grace'),
	 ('Home Office','MG-17890','Michael Granlund'),
	 ('Consumer','MG-18145','Mike Gockenbach'),
	 ('Corporate','MG-18205','Mitch Gastineau'),
	 ('Home Office','MH-17290','Marc Harrigan');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','MH-17440','Mark Haberlin'),
	 ('Consumer','MH-17455','Mark Hamilton'),
	 ('Corporate','MH-17620','Matt Hagelstein'),
	 ('Corporate','MH-17785','Maya Herman'),
	 ('Consumer','MH-18025','Michelle Huthwaite'),
	 ('Home Office','MH-18115','Mick Hernandez'),
	 ('Consumer','MJ-17740','Max Jones'),
	 ('Corporate','MK-17905','Michael Kennedy'),
	 ('Consumer','MK-18160','Mike Kennedy'),
	 ('Corporate','ML-17395','Marina Lichtenstein');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','ML-17410','Maris LaWare'),
	 ('Home Office','ML-17755','Max Ludwig'),
	 ('Corporate','ML-18040','Michelle Lonsdale'),
	 ('Consumer','ML-18265','Muhammed Lee'),
	 ('Consumer','MM-17260','Magdelene Morse'),
	 ('Consumer','MM-17920','Michael Moore'),
	 ('Consumer','MM-18055','Michelle Moray'),
	 ('Corporate','MM-18280','Muhammed MacIntyre'),
	 ('Consumer','MN-17935','Michael Nguyen'),
	 ('Consumer','MO-17500','Mary O''Rourke');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Home Office','MO-17800','Meg O''Connel'),
	 ('Consumer','MO-17950','Michael Oakman'),
	 ('Home Office','MP-17470','Mark Packer'),
	 ('Corporate','MP-17965','Michael Paige'),
	 ('Home Office','MP-18175','Mike Pelletier'),
	 ('Home Office','MR-17545','Mathew Reese'),
	 ('Consumer','MS-17365','Maribeth Schnelling'),
	 ('Consumer','MS-17530','MaryBeth Skach'),
	 ('Consumer','MS-17710','Maurice Satty'),
	 ('Consumer','MS-17770','Maxwell Schwartz');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','MS-17830','Melanie Seite'),
	 ('Corporate','MS-17980','Michael Stewart'),
	 ('Consumer','MT-17815','Meg Tillman'),
	 ('Home Office','MT-18070','Michelle Tran'),
	 ('Consumer','MV-17485','Mark Van Huff'),
	 ('Consumer','MV-18190','Mike Vittorini'),
	 ('Consumer','MW-18220','Mitch Webber'),
	 ('Corporate','MW-18235','Mitch Willingham'),
	 ('Corporate','MY-17380','Maribeth Yedwab'),
	 ('Corporate','MY-18295','Muhammed Yedwab');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Home Office','MZ-17335','Maria Zettner'),
	 ('Corporate','MZ-17515','Mary Zewe'),
	 ('Corporate','NB-18580','Nicole Brennan'),
	 ('Corporate','NB-18655','Nona Balk'),
	 ('Consumer','NC-18340','Nat Carroll'),
	 ('Consumer','NC-18415','Nathan Cano'),
	 ('Corporate','NC-18535','Nick Crebassa'),
	 ('Corporate','NC-18625','Noah Childs'),
	 ('Consumer','ND-18370','Natalie DeCherney'),
	 ('Corporate','ND-18460','Neil Ducich');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','NF-18385','Natalie Fritzler'),
	 ('Home Office','NF-18475','Neil Französisch'),
	 ('Home Office','NF-18595','Nicole Fjeld'),
	 ('Corporate','NG-18355','Nat Gilpin'),
	 ('Consumer','NG-18430','Nathan Gelder'),
	 ('Corporate','NH-18610','Nicole Hansen'),
	 ('Home Office','NK-18490','Neil Knudson'),
	 ('Home Office','NL-18310','Nancy Lomonaco'),
	 ('Home Office','NM-18445','Nathan Mautz'),
	 ('Consumer','NM-18520','Neoma Murray');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','NP-18325','Naresj Patel'),
	 ('Consumer','NP-18670','Nora Paige'),
	 ('Home Office','NP-18685','Nora Pelletier'),
	 ('Consumer','NP-18700','Nora Preis'),
	 ('Consumer','NR-18550','Nick Radford'),
	 ('Consumer','NS-18505','Neola Schneider'),
	 ('Corporate','NS-18640','Noel Staavos'),
	 ('Consumer','NW-18400','Natalie Webber'),
	 ('Home Office','NZ-18565','Nick Zandusky'),
	 ('Corporate','ON-18715','Odella Nelson');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','OT-18730','Olvera Toch'),
	 ('Home Office','PA-19060','Pete Armstrong'),
	 ('Home Office','PB-18805','Patrick Bzostek'),
	 ('Consumer','PB-19105','Peter Bühler'),
	 ('Consumer','PB-19150','Philip Brown'),
	 ('Corporate','PB-19210','Phillip Breyer'),
	 ('Corporate','PC-18745','Pamela Coakley'),
	 ('Home Office','PC-19000','Pauline Chand'),
	 ('Consumer','PF-19120','Peter Fuller'),
	 ('Consumer','PF-19165','Philip Fox');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','PF-19225','Phillip Flathmann'),
	 ('Consumer','PG-18820','Patrick Gardner'),
	 ('Consumer','PG-18895','Paul Gonzalez'),
	 ('Home Office','PH-18790','Patricia Hirasaki'),
	 ('Corporate','PJ-18835','Patrick Jones'),
	 ('Consumer','PJ-19015','Pauline Johnson'),
	 ('Home Office','PK-18910','Paul Knutson'),
	 ('Consumer','PK-19075','Pete Kriz'),
	 ('Home Office','PL-18925','Paul Lucas'),
	 ('Consumer','PM-18940','Paul MacIntyre');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Home Office','PM-19135','Peter McVee'),
	 ('Home Office','PN-18775','Parhena Norris'),
	 ('Consumer','PO-18850','Patrick O''Brill'),
	 ('Consumer','PO-18865','Patrick O''Donnell'),
	 ('Home Office','PO-19180','Philisse Overcash'),
	 ('Home Office','PO-19195','Phillina Ober'),
	 ('Home Office','PP-18955','Paul Prost'),
	 ('Consumer','PR-18880','Patrick Ryan'),
	 ('Consumer','PS-18760','Pamela Stobb'),
	 ('Home Office','PS-18970','Paul Stevenson');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Home Office','PS-19045','Penelope Sewall'),
	 ('Consumer','PT-19090','Pete Takahito'),
	 ('Home Office','PV-18985','Paul Van Hugh'),
	 ('Corporate','PW-19030','Pauline Webber'),
	 ('Consumer','PW-19240','Pierre Wener'),
	 ('Corporate','QJ-19255','Quincy Jones'),
	 ('Consumer','RA-19285','Ralph Arnett'),
	 ('Corporate','RA-19885','Ruben Ausman'),
	 ('Consumer','RA-19915','Russell Applegate'),
	 ('Consumer','RA-19945','Ryan Akin');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','RB-19330','Randy Bradley'),
	 ('Consumer','RB-19360','Raymond Buch'),
	 ('Consumer','RB-19435','Richard Bierner'),
	 ('Home Office','RB-19465','Rick Bensley'),
	 ('Consumer','RB-19570','Rob Beeghly'),
	 ('Corporate','RB-19645','Robert Barroso'),
	 ('Home Office','RB-19705','Roger Barcio'),
	 ('Home Office','RB-19795','Ross Baird'),
	 ('Consumer','RC-19825','Roy Collins'),
	 ('Consumer','RC-19960','Ryan Crowe');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','RD-19480','Rick Duston'),
	 ('Consumer','RD-19585','Rob Dowd'),
	 ('Home Office','RD-19660','Robert Dilbeck'),
	 ('Consumer','RD-19720','Roger Demir'),
	 ('Home Office','RD-19810','Ross DeVincentis'),
	 ('Consumer','RD-19900','Ruben Dartt'),
	 ('Consumer','RD-19930','Russell D''Ascenzo'),
	 ('Consumer','RE-19405','Ricardo Emerson'),
	 ('Consumer','RE-19450','Richard Eichhorn'),
	 ('Corporate','RF-19345','Randy Ferguson');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','RF-19735','Roland Fjeld'),
	 ('Consumer','RF-19840','Roy Französisch'),
	 ('Consumer','RH-19495','Rick Hansen'),
	 ('Home Office','RH-19510','Rick Huthwaite'),
	 ('Consumer','RH-19555','Ritsa Hightower'),
	 ('Consumer','RH-19600','Rob Haberlin'),
	 ('Consumer','RK-19300','Ralph Kennedy'),
	 ('Consumer','RL-19615','Rob Lucas'),
	 ('Consumer','RM-19375','Raymond Messe'),
	 ('Home Office','RM-19675','Robert Marley');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','RM-19750','Roland Murray'),
	 ('Consumer','RO-19780','Rose O''Brian'),
	 ('Corporate','RP-19270','Rachel Payne'),
	 ('Consumer','RP-19390','Resi Pölking'),
	 ('Corporate','RP-19855','Roy Phan'),
	 ('Consumer','RR-19315','Ralph Ritter'),
	 ('Corporate','RR-19525','Rick Reed'),
	 ('Corporate','RS-19420','Ricardo Sperren'),
	 ('Corporate','RS-19765','Roland Schwarz'),
	 ('Home Office','RS-19870','Roy Skaria');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','RW-19540','Rick Wilson'),
	 ('Corporate','RW-19630','Rob Williams'),
	 ('Consumer','RW-19690','Robert Waldorf'),
	 ('Consumer','SA-20830','Sue Ann Reed'),
	 ('Consumer','SB-20170','Sarah Bern'),
	 ('Consumer','SB-20185','Sarah Brown'),
	 ('Corporate','SB-20290','Sean Braxton'),
	 ('Consumer','SC-20020','Sam Craven'),
	 ('Home Office','SC-20050','Sample Company A'),
	 ('Consumer','SC-20095','Sanjit Chand');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','SC-20230','Scot Coram'),
	 ('Corporate','SC-20260','Scott Cohen'),
	 ('Consumer','SC-20305','Sean Christensen'),
	 ('Consumer','SC-20380','Shahid Collister'),
	 ('Corporate','SC-20440','Shaun Chance'),
	 ('Consumer','SC-20575','Sonia Cooley'),
	 ('Home Office','SC-20680','Steve Carroll'),
	 ('Corporate','SC-20695','Steve Chapman'),
	 ('Consumer','SC-20725','Steven Cartwright'),
	 ('Corporate','SC-20770','Stewart Carmichael');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','SC-20800','Stuart Calhoun'),
	 ('Consumer','SC-20845','Sung Chung'),
	 ('Home Office','SD-20485','Shirley Daniels'),
	 ('Consumer','SE-20110','Sanjit Engle'),
	 ('Consumer','SF-20065','Sandra Flanagan'),
	 ('Consumer','SF-20200','Sarah Foster'),
	 ('Corporate','SF-20965','Sylvia Foulston'),
	 ('Consumer','SG-20080','Sandra Glassco'),
	 ('Consumer','SG-20470','Sheri Gordon'),
	 ('Consumer','SG-20605','Speros Goranitis');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','SG-20890','Susan Gilcrest'),
	 ('Corporate','SH-19975','Sally Hughsby'),
	 ('Consumer','SH-20395','Shahid Hopkins'),
	 ('Corporate','SH-20635','Stefanie Holloman'),
	 ('Home Office','SJ-20125','Sanjit Jacobs'),
	 ('Consumer','SJ-20215','Sarah Jordon'),
	 ('Consumer','SJ-20500','Shirley Jackson'),
	 ('Consumer','SK-19990','Sally Knutson'),
	 ('Home Office','SL-20155','Sara Luxemburg'),
	 ('Consumer','SM-20005','Sally Matthias');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Home Office','SM-20320','Sean Miller'),
	 ('Consumer','SM-20905','Susan MacKendrick'),
	 ('Corporate','SM-20950','Suzanne McNair'),
	 ('Home Office','SN-20560','Skye Norling'),
	 ('Home Office','SN-20710','Steve Nguyen'),
	 ('Consumer','SO-20335','Sean O''Donnell'),
	 ('Corporate','SP-20545','Sibella Parks'),
	 ('Corporate','SP-20620','Stefania Perrino'),
	 ('Corporate','SP-20650','Stephanie Phelps'),
	 ('Corporate','SP-20860','Sung Pak');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','SP-20920','Susan Pistek'),
	 ('Home Office','SR-20425','Sharelle Roach'),
	 ('Home Office','SR-20740','Steven Roelle'),
	 ('Corporate','SS-20140','Saphhira Shifley'),
	 ('Consumer','SS-20410','Shahid Shariari'),
	 ('Home Office','SS-20515','Shirley Schmidt'),
	 ('Consumer','SS-20590','Sonia Sunley'),
	 ('Consumer','SS-20875','Sung Shariari'),
	 ('Consumer','ST-20530','Shui Tom'),
	 ('Home Office','SU-20665','Stephanie Ulpright');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','SV-20365','Seth Vernon'),
	 ('Consumer','SV-20785','Stewart Visinsky'),
	 ('Corporate','SV-20815','Stuart Van'),
	 ('Consumer','SV-20935','Susan Vittorini'),
	 ('Consumer','SW-20245','Scot Wooten'),
	 ('Consumer','SW-20275','Scott Williamson'),
	 ('Home Office','SW-20350','Sean Wendt'),
	 ('Consumer','SW-20455','Shaun Weien'),
	 ('Corporate','SW-20755','Steven Ward'),
	 ('Home Office','SZ-20035','Sam Zeldin');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Home Office','TA-21385','Tom Ashbrook'),
	 ('Consumer','TB-21055','Ted Butterfield'),
	 ('Corporate','TB-21175','Thomas Boland'),
	 ('Home Office','TB-21190','Thomas Brumley'),
	 ('Consumer','TB-21250','Tim Brockman'),
	 ('Consumer','TB-21280','Toby Braunhardt'),
	 ('Corporate','TB-21355','Todd Boyes'),
	 ('Consumer','TB-21400','Tom Boeckenhauer'),
	 ('Consumer','TB-21520','Tracy Blumstein'),
	 ('Consumer','TB-21595','Troy Blackwell');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','TB-21625','Trudy Brown'),
	 ('Corporate','TC-20980','Tamara Chand'),
	 ('Corporate','TC-21145','Theresa Coyne'),
	 ('Consumer','TC-21295','Toby Carlisle'),
	 ('Home Office','TC-21475','Tony Chapman'),
	 ('Home Office','TC-21535','Tracy Collins'),
	 ('Consumer','TD-20995','Tamara Dahlen'),
	 ('Consumer','TG-21310','Toby Gnade'),
	 ('Consumer','TG-21640','Trudy Glocke'),
	 ('Consumer','TH-21100','Thea Hendricks');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','TH-21115','Thea Hudgings'),
	 ('Corporate','TH-21235','Tiffany House'),
	 ('Home Office','TH-21550','Tracy Hopkins'),
	 ('Consumer','TM-21010','Tamara Manning'),
	 ('Consumer','TM-21490','Tony Molinari'),
	 ('Home Office','TN-21040','Tanja Norvell'),
	 ('Consumer','TP-21130','Theone Pippenger'),
	 ('Consumer','TP-21415','Tom Prescott'),
	 ('Corporate','TP-21565','Tracy Poddar'),
	 ('Consumer','TR-21325','Toby Ritter');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','TS-21085','Thais Sissman'),
	 ('Corporate','TS-21160','Theresa Swint'),
	 ('Corporate','TS-21205','Thomas Seio'),
	 ('Consumer','TS-21340','Toby Swindell'),
	 ('Corporate','TS-21370','Todd Sumrall'),
	 ('Corporate','TS-21430','Tom Stivers'),
	 ('Consumer','TS-21505','Tony Sayre'),
	 ('Consumer','TS-21610','Troy Staebel'),
	 ('Consumer','TS-21655','Trudy Schmidt'),
	 ('Consumer','TT-21070','Ted Trevino');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Consumer','TT-21220','Thomas Thornton'),
	 ('Corporate','TT-21265','Tim Taslimi'),
	 ('Home Office','TT-21460','Tonja Turnell'),
	 ('Home Office','TW-21025','Tamara Willingham'),
	 ('Consumer','TZ-21580','Tracy Zic'),
	 ('Corporate','VB-21745','Victoria Brennan'),
	 ('Consumer','VD-21670','Valerie Dominguez'),
	 ('Home Office','VF-21715','Vicky Freymann'),
	 ('Consumer','VG-21790','Vivek Gonzalez'),
	 ('Corporate','VG-21805','Vivek Grady');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Home Office','VM-21685','Valerie Mitchum'),
	 ('Consumer','VM-21835','Vivian Mathis'),
	 ('Home Office','VP-21730','Victor Preis'),
	 ('Corporate','VP-21760','Victoria Pisteka'),
	 ('Consumer','VS-21820','Vivek Sundaresam'),
	 ('Home Office','VT-21700','Valerie Takahito'),
	 ('Corporate','VW-21775','Victoria Wilson'),
	 ('Consumer','WB-21850','William Brown'),
	 ('Consumer','XP-21865','Xylona Preis'),
	 ('Corporate','YC-21895','Yoseph Carroll');
INSERT INTO public.customers (segment,customer_id,customer_name) VALUES
	 ('Corporate','YS-21880','Yana Sorensen'),
	 ('Consumer','ZC-21910','Zuschuss Carroll'),
	 ('Consumer','ZD-21925','Zuschuss Donatelli');
